### ISSUE TITLE
Routes should be lowercased and different

### ISSUE THREAD

**Issue by prokopsimek** [ButterCMS/dotnet-starter-buttercms#3]
List now: https://dotnet-starter-buttercms.azurewebsites.net/Blog
List after: https://dotnet-starter-buttercms.azurewebsites.net/blog

Detail now: https://dotnet-starter-buttercms.azurewebsites.net/Blog/Post/example-post
Detail after: https://dotnet-starter-buttercms.azurewebsites.net/blog/example-post

Category now: https://dotnet-starter-buttercms.azurewebsites.net/Blog?categorySlug=example-category
Category after: https://dotnet-starter-buttercms.azurewebsites.net/blog/category/example-category

Tag now: https://dotnet-starter-buttercms.azurewebsites.net/Blog?tagSlug=example-tag
Tag after: https://dotnet-starter-buttercms.azurewebsites.net/blog/tag/example-tag

Search now: https://dotnet-starter-buttercms.azurewebsites.net/Blog?SearchQuery=asff
Serach after: https://dotnet-starter-buttercms.azurewebsites.net/blog/search/?q=asff

**Comment by vlnevyhosteny** [comment]
@prokopsimek Is that mandatory? Because my implementation is following .NET naming conventions, although I admit it's strange from Nodejs dev point of view. 

- https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions
- https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-6.0

I can change it but it won't fit .NET conventions 100% .

**Comment by vlnevyhosteny** [comment]
As I am thinking about that I will convert it to conventional format.
